mode: ContinuousDelivery
next-version: 1.0.0
branches:
  main:
    regex: ^main$|^master$
    increment: Patch
  feature:
    regex: ^features?[/-]
    increment: Inherit
  release:
    regex: ^releases?[/-]
    increment: Patch
