-- Generated SQL file to drop tables

DROP TABLE IF EXISTS t_admin CASCADE;
DROP TABLE IF EXISTS t_comment CASCADE;
DROP TABLE IF EXISTS t_pdc CASCADE;
DROP TABLE IF EXISTS t_pers CASCADE;
DROP TABLE IF EXISTS t_subjects CASCADE;
DROP TABLE IF EXISTS t_teams CASCADE;
DROP TABLE IF EXISTS t_teams_managers CASCADE;
